mappings = {
    "HP_HP_MAPPINGS": """CREATE TABLE EXOMISER.HP_HP_MAPPINGS_SCRAMBLE (
	MAPPING_ID INTEGER,
	HP_ID VARCHAR(10),
	HP_TERM VARCHAR(200),
	HP_ID_HIT VARCHAR(10),
	HP_HIT_TERM VARCHAR(200),
	SIMJ DOUBLE,
	IC DOUBLE,
	SCORE DOUBLE,
	LCS_ID VARCHAR(20),
	LCS_TERM VARCHAR(150)
);""",
    "HP_MP_MAPPINGS": """CREATE TABLE EXOMISER.HP_MP_MAPPINGS_SCRAMBLE (
	MAPPING_ID INTEGER,
	HP_ID VARCHAR(10),
	HP_TERM VARCHAR(200),
	ZP_ID VARCHAR(10),
	ZP_TERM VARCHAR(200),
	SIMJ DOUBLE,
	IC DOUBLE,
	SCORE DOUBLE,
	LCS_ID VARCHAR(40),
	LCS_TERM VARCHAR(150)
);""",
    "HP_ZP_MAPPINGS": """CREATE TABLE EXOMISER.HP_ZP_MAPPINGS_SCRAMBLE (
	MAPPING_ID INTEGER,
	HP_ID VARCHAR(10),
	HP_TERM VARCHAR(200),
	ZP_ID VARCHAR(10),
	ZP_TERM VARCHAR(200),
	SIMJ DOUBLE,
	IC DOUBLE,
	SCORE DOUBLE,
	LCS_ID VARCHAR(40),
	LCS_TERM VARCHAR(150)
);""",
}
